name: CI Build

permissions: read-all

on:
  push:
    branches: [ master-kela ]
  pull_request:
    branches: [ master-kela ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ARM SDK
        run: make arm_sdk_install

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Build IFLIGHT_BLITZ_F435
      run: make IFLIGHT_BLITZ_F435

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Firmware
        path: |
          obj/*.hex
          obj/*.bin
        if-no-files-found: warn
