name: CI Build

on:
  push:
    branches: [ master-kela ]
  pull_request:
    branches: [ master-kela ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-arm-none-eabi libnewlib-arm-none-eabi
    
    - name: Build IFLIGHT_BLITZ_F435
      run: make IFLIGHT_BLITZ_F435
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          obj/*.hex
          obj/*.bin
        if-no-files-found: warn
